name: Test Pull Request
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Report Coverage
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests and generate coverage
      - name: Run tests
        run: npm run test:coverage
